In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/heart_disease_uci.csv')

In [ ]:
# First 5 rows
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [ ]:
# Dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB

In [ ]:

df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [ ]:
categorical_cols=df.select_dtypes(include=['object']).columns
print("categorical features:",categorical_cols)

categorical features: Index(['sex', 'dataset', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal'], dtype='object')

In [ ]:
numerical_cols=df.select_dtypes(include=['int64','float64']).columns
print("numerical features:",numerical_cols)

numerical features: Index(['id', 'age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca', 'num'], dtype='object')

In [ ]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.fillna(df.mean(numeric_only=True),inplace=True)

In [ ]:
df=pd.get_dummies(df,drop_first=True)
df

,id,age,trestbps,chol,thalch,oldpeak,ca,num,sex_Male,dataset_Hungary,...,cp_non-anginal,cp_typical angina,fbs_True,restecg_normal,restecg_st-t abnormality,exang_True,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,1,63,145.0,233.0,150.0,2.3,0.0,0,True,False,...,False,True,True,False,False,False,False,False,False,False
1,2,67,160.0,286.0,108.0,1.5,3.0,2,True,False,...,False,False,False,False,False,True,True,False,True,False
2,3,67,120.0,229.0,129.0,2.6,2.0,1,True,False,...,False,False,False,False,False,True,True,False,False,True
3,4,37,130.0,250.0,187.0,3.5,0.0,0,True,False,...,True,False,False,True,False,False,False,False,True,False
4,5,41,130.0,204.0,172.0,1.4,0.0,0,False,False,...,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,300,68,144.0,193.0,141.0,3.4,2.0,2,True,False,...,False,False,True,True,False,False,True,False,False,True
300,301,57,130.0,131.0,115.0,1.2,1.0,3,True,False,...,False,False,False,True,False,True,True,False,False,True
301,302,57,130.0,236.0,174.0,0.0,1.0,1,False,False,...,False,False,False,False,False,False,True,False,True,False
508,509,47,150.0,226.0,98.0,1.5,0.0,1,True,True,...,False,False,False,True,False,True,True,False,False,True
748,749,56,120.0,100.0,120.0,1.5,0.0,1,True,False,...,False,False,False,True,False,True,True,False,False,True

In [ ]:
print(df.columns)

Index(['id', 'age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca', 'num',
       'sex_Male', 'dataset_Hungary', 'dataset_VA Long Beach',
       'cp_atypical angina', 'cp_non-anginal', 'cp_typical angina', 'fbs_True',
       'restecg_normal', 'restecg_st-t abnormality', 'exang_True',
       'slope_flat', 'slope_upsloping', 'thal_normal',
       'thal_reversable defect'],
      dtype='object')

In [ ]:
df['target'] = df['num'].apply(lambda x: 1 if x > 0 else 0)

In [ ]:

df

,age,trestbps,chol,thalch,oldpeak,ca,sex_Male,dataset_Hungary,dataset_VA Long Beach,cp_atypical angina,...,cp_typical angina,fbs_True,restecg_normal,restecg_st-t abnormality,exang_True,slope_flat,slope_upsloping,thal_normal,thal_reversable defect,target
0,63,145.0,233.0,150.0,2.3,0.0,True,False,False,False,...,True,True,False,False,False,False,False,False,False,0
1,67,160.0,286.0,108.0,1.5,3.0,True,False,False,False,...,False,False,False,False,True,True,False,True,False,1
2,67,120.0,229.0,129.0,2.6,2.0,True,False,False,False,...,False,False,False,False,True,True,False,False,True,1
3,37,130.0,250.0,187.0,3.5,0.0,True,False,False,False,...,False,False,True,False,False,False,False,True,False,0
4,41,130.0,204.0,172.0,1.4,0.0,False,False,False,True,...,False,False,False,False,False,False,True,True,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,68,144.0,193.0,141.0,3.4,2.0,True,False,False,False,...,False,True,True,False,False,True,False,False,True,1
300,57,130.0,131.0,115.0,1.2,1.0,True,False,False,False,...,False,False,True,False,True,True,False,False,True,1
301,57,130.0,236.0,174.0,0.0,1.0,False,False,False,True,...,False,False,False,False,False,True,False,True,False,1
508,47,150.0,226.0,98.0,1.5,0.0,True,True,False,False,...,False,False,True,False,True,True,False,False,True,1
748,56,120.0,100.0,120.0,1.5,0.0,True,False,True,False,...,False,False,True,False,True,True,False,False,True,1

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = df.drop('target', axis=1)
y = df['target']

In [ ]:

X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

Confusion Matrix:
 [[32  3]
 [ 3 22]]

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_scaled, y, cv=5)
print("Cross Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())

Cross Validation Scores: [0.85       0.9        0.78333333 0.83333333 0.77966102]
Mean Accuracy: 0.8292655367231638

In [ ]:
model.predict(X_test)

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [ ]:
model.predict_proba(X_test)

array([[0.00989872, 0.99010128],
       [0.96548972, 0.03451028],
       [0.43373934, 0.56626066],
       [0.14225447, 0.85774553],
       [0.88469532, 0.11530468],
       [0.08571397, 0.91428603],
       [0.98884608, 0.01115392],
       [0.19190148, 0.80809852],
       [0.9069616 , 0.0930384 ],
       [0.00921797, 0.99078203],
       [0.66717786, 0.33282214],
       [0.96739436, 0.03260564],
       [0.94406756, 0.05593244],
       [0.00581103, 0.99418897],
       [0.69516293, 0.30483707],
       [0.27326134, 0.72673866],
       [0.84770767, 0.15229233],
       [0.27171065, 0.72828935],
       [0.99406788, 0.00593212],
       [0.47509944, 0.52490056],
       [0.21068198, 0.78931802],
       [0.77108617, 0.22891383],
       [0.23844097, 0.76155903],
       [0.96059195, 0.03940805],
       [0.58207623, 0.41792377],
       [0.8145068 , 0.1854932 ],
       [0.29266613, 0.70733387],
       [0.94181335, 0.05818665],
       [0.98782245, 0.01217755],
       [0.8910661 , 0.1089339 ],
       [0.69923331, 0.30076669],
       [0.94764881, 0.05235119],
       [0.30496909, 0.69503091],
       [0.00543649, 0.99456351],
       [0.33883792, 0.66116208],
       [0.83639422, 0.16360578],
       [0.53552947, 0.46447053],
       [0.58843318, 0.41156682],
       [0.93542894, 0.06457106],
       [0.98905051, 0.01094949],
       [0.9508311 , 0.0491689 ],
       [0.93869283, 0.06130717],
       [0.02586595, 0.97413405],
       [0.01496703, 0.98503297],
       [0.67208593, 0.32791407],
       [0.95433608, 0.04566392],
       [0.04918702, 0.95081298],
       [0.00887256, 0.99112744],
       [0.99724145, 0.00275855],
       [0.2734021 , 0.7265979 ],
       [0.97300459, 0.02699541],
       [0.20793604, 0.79206396],
       [0.88743312, 0.11256688],
       [0.03054921, 0.96945079],
       [0.96936208, 0.03063792],
       [0.24231897, 0.75768103],
       [0.06983117, 0.93016883],
       [0.96634833, 0.03365167],
       [0.79868464, 0.20131536],
       [0.55144845, 0.44855155]])